AWSTemplateFormatVersion: "2010-09-09"
Description: Discord Bot infrastructure

Parameters:
    DiscordToken:
        Type: String
        Description: Discord Bot Security Token

Resources:
    DiscordBotToken:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: /discord-bot/DISCORD_BOT_TOKEN
            Type: String
            Value: !Ref DiscordToken
            Description: "Discord Bot Security Token"
    Repository:
        Type: "AWS::ECR::Repository"
        Properties:
            RepositoryName: "discord-bot"
            EmptyOnDelete: true
