AWSTemplateFormatVersion: "2010-09-09"
Description: Discord Bot infrastructure

Parameters:
    Token:
        Type: String
        Description: Bot Security Token

Resources:
    DicordBotToken:
        Type: "AWS::SSM::Parameter"
        Properties:
            Name: disco-bot/DISCORD_BOT_TOKEN
            Type: SecureString
            Value: !Ref Discord-Token
            Description: "Discord Bot Security Token"
