name: Deploy

on:
    workflow_dispatch:
    release:
        types: [published]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: aws/prod
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        steps:
            - uses: actions/checkout@v4

            - name: Provision infrastructure
              run: |
                  aws cloudformation deploy \
                  --template-file infra/aws.yaml \
                  --stack-name Discord-Bot-Service \
                  --parameter-overrides \
                        DiscordToken=${{ secrets.DISCORD_BOT_TOKEN }} \
                        DockerImage=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
                        ContainerRegistryAccessToken=${{ secrets.GHCR_TOKEN }} \
                  --capabilities CAPABILITY_IAM
