name: Destroy

on:
    workflow_dispatch:

jobs:
    destroy:
        environment: aws/prod
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
        runs-on: ubuntu-latest
        steps:
            - name: Destroy Infrastructure
              run: aws cloudformation delete-stack --stack-name Discord-Bot-Service
